# Generated by Django 5.2.17 on 2026-08-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=128)),
                ('away_team', models.CharField(max_length=128)),
                ('home_odds', models.FloatField(blank=True, null=True)),
                ('away_odds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'home_team', 'away_team'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_win_prob', models.FloatField()),
                ('away_win_prob', models.FloatField()),
                ('model_version', models.CharField(default='logreg_odds_v1', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='core.game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
